version: '3.8'
services:
  database:
    image: postgres:15
    container_name: hogwarts_bar_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5030
      POSTGRES_DB: hogwarts_bar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hogwarts_bar_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 5030
      DATABASE_NAME: hogwarts_bar
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
